[package]
name = "vitagl-sys"
version = "0.1.2"
edition = "2021"
description = "Low-level bindings for the vitaGL library"
license = "MIT"
repository = "https://github.com/Exotik850/vitagl-sys"

[dependencies]

[features]
bindgen = ["dep:bindgen"]

[package.metadata.vita]
# this is a placeholder, and will be updated with the actual
# title ID of the downstream crate that depends on this one
title_id = "VITAGL000"

[build-dependencies]
bindgen = { version = "0.72", optional = true }

[[example]]
name = "cube"
path = "./examples/cube.rs"

[dev-dependencies]
vita-dbgscreen = "0.1.2"
